
development:
  adapter: postgresql
  encoding: unicode
  database: melindalini_development
  pool: 5
  username: melindalini
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: melindalini_test
  pool: 5
  username: melindalini
  password:
